events {}

http {
    # Balanceador de carga hacia 2 copias de FastAPI
    upstream fastapi_backend {
        server api1:8000;
        server api2:8000;
    }

    server {
        listen 80;
        server_name mercyreact.duckdns.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name mercyreact.duckdns.org;

        ssl_certificate /etc/letsencrypt/live/mercyreact.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mercyreact.duckdns.org/privkey.pem;

        # Redirigir el tráfico de la API y Docs a FastAPI
        location /api {
            proxy_pass http://fastapi_backend;
        }
        location /docs {
            proxy_pass http://fastapi_backend;
        }
        location /openapi.json {
            proxy_pass http://fastapi_backend;
        }

        # Redirigir el resto del tráfico web a Flask
        location / {
            proxy_pass http://web:5000;
        }
    }
}
