events {}

http {
    # Balanceador de carga hacia 2 copias de FastAPI
    upstream fastapi_backend {
        server api1:8000;
        server api2:8000;
    }

    upstream grafana_backend {
        server grafana:3000;
    }

    log_format upstreamlog '$remote_addr - [$time_local] "$request" $status --> RESPONDIDO POR: $upstream_addr';
    
    server {
        listen 80;
        server_name mercyreact.duckdns.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name mercyreact.duckdns.org;
        
        access_log /dev/stdout upstreamlog;

        ssl_certificate /etc/letsencrypt/live/mercyreact.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mercyreact.duckdns.org/privkey.pem;

        # Redirigir llamadas de administración de Flask
        location /api/admin/ {
            proxy_pass http://web:5000;
        }

        # Redirigir el tráfico de la API móvil y Docs a FastAPI
        location /api/ {
            proxy_pass http://fastapi_backend;
        }
        location /docs {
            proxy_pass http://fastapi_backend;
        }
        location /openapi.json {
            proxy_pass http://fastapi_backend;
        }

        # Redirigir Grafana a través de Nginx (Seguro HTTPS)
        location /grafana/ {
            proxy_pass http://grafana_backend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Redirigir el resto del tráfico web a Flask
        location / {
            proxy_pass http://web:5000;
        }
    }
}
