events {}

http {
    upstream fastapi_backend {
        server api1:8000;
        server api2:8000;
    }



    log_format upstreamlog '$remote_addr - [$time_local] "$request" $status --> RESPONDIDO POR: $upstream_addr';
    
    server {
        listen 80;
        server_name mercyreact.duckdns.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name mercyreact.duckdns.org;
        
        access_log /dev/stdout upstreamlog;

        ssl_certificate /etc/letsencrypt/live/mercyreact.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mercyreact.duckdns.org/privkey.pem;

        # Redirigir llamadas de administración de Flask
        location /api/admin/ {
            proxy_pass http://web:5000;
        }

        # Redirigir el tráfico de la API móvil y Docs a FastAPI
        location /api/ {
            proxy_pass http://fastapi_backend;
        }
        location /docs {
            proxy_pass http://fastapi_backend;
        }
        location /openapi.json {
            proxy_pass http://fastapi_backend;
        }

        # Grafana se accederá directamente por el puerto 3000

        # Redirigir el resto del tráfico web a Flask
        location / {
            proxy_pass http://web:5000;
        }
    }
}
