events {
    worker_connections 1024;
}

http {
    # Balanceador de carga
    upstream mercy_api {
        # El método de balanceo por defecto es Round-Robin (distribución equitativa)
        server api_privada:8000;
        # Aquí se agregarían más servidores para escalar:
        # server api_privada_2:8000;
        # server api_privada_3:8000;
    }

    server {
        listen 80;
        server_name api.mercy.com;

        # Redirigir tráfico HTTP a HTTPS
        # return 301 https://$host$request_uri;

        location / {
            proxy_pass http://mercy_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_addrs;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Rate limiting / WAF features can be added here
        }
    }
    
    # Configuración SSL (Descomentar al tener certificados reales)
    # server {
    #     listen 443 ssl;
    #     server_name api.mercy.com;
    #     ssl_certificate /etc/nginx/certs/fullchain.pem;
    #     ssl_certificate_key /etc/nginx/certs/privkey.pem;
    #     
    #     location / {
    #         proxy_pass http://mercy_api;
    #     }
    # }
}
